### ISSUE TITLE
Arch Linux identified as Linux

### ISSUE THREAD

**Issue by AdJaGu** [HorlogeSkynet/Archey4#1]
In the following screenshot you can see that Archey4 and lsb_release -d both return Arch Linux. This being the case why does Archey4 display the Linux penguin graphic instead of the Arch Linux one?

![screenshot_2017-06-18_20-09-20](https://user-images.githubusercontent.com/6255623/27265354-1e5ec82a-5462-11e7-8758-dfd34ec1e9ca.png)

**Comment by HorlogeSkynet** [comment]
Oh... That's so sad. Actually, I haven't tested it under a x86 Arch ; I was waiting for someone does 😄

The script uses the output of `lsb_release -i -s`, could you give me what you have on your system ? Thank you !

**Comment by AdJaGu** [comment]
`lsb_release -i -s` returns `Arch`.

**Comment by HorlogeSkynet** [comment]
I see, it is acting pretty weird indeed. On another system I've got an Arch Linux ARM, and the output is the expected `Arch Linux` with the `-i` option though.

Tomorrow I'll start to consider this very case (with another improvement on the same idea too), stay tuned 👌
Thanks again for the feedback

**Comment by HorlogeSkynet** [comment]
Okay, I've changed the distribution detection stuff among others things, tell me if everything is okay with your system now !

And... don't forget to close this issue if you think it deserves it 😉

**Comment by AdJaGu** [comment]
@HorlogeSkynet It works as expected now and displays proper logo and information. Thank you.
