### ISSUE TITLE
[BUG] Uptime reported incorrectly on macOS

### ISSUE THREAD

**Issue by staceybellerose** [HorlogeSkynet/archey4#105]
**Describe the bug**
The uptime displayed on macOS is incorrect and does not match the time reported by `uptime`.

**Expected behavior**
The uptime displayed matches the time reported by `uptime`.

**Screenshots**
<img width="592" alt="Screen Shot 2021-11-11 at 8 08 09 PM" src="https://user-images.githubusercontent.com/1043355/141396733-a997d376-b4ae-4516-9ec3-59e567330797.png">

**Environment**

 - Version used (4.Y.Z) : v4.13.2
 - Method of installation (distribution package, PyPI, Homebrew, sources) : Homebrew
 - Hardware type (laptop, server, Raspberry, hyper-visor) : laptop
 - Python version (3.Y.Z) : 3.9.7
 - Operating system and version : macOS Catalina 10.15.7
 - Graphical environment name and version : macOS
 - Connectivity (off-line, LAN only, Internet access) : Internet access

**Additional context**
N/A

**Comment by HorlogeSkynet** [comment]
Hey @staceybellerose, thanks for opening this up.
It looks like we are dealing with inconsistencies related to Python's `time.CLOCK_UPTIME_RAW` behavior (Python 3.8+, macOS 10.12+).
Returned value does not take into account the time the system spent being asleep.
I'll try to fix this soon. Bye 👋

**Comment by HorlogeSkynet** [comment]
Just released as [v4.13.3](https://github.com/HorlogeSkynet/archey4/releases/tag/v4.13.3), on its way to Homebrew : Homebrew/homebrew-core#89334

Bye :wave:
