### ISSUE TITLE
[BUG] in README

### ISSUE THREAD

**Issue by fyrefiend** [HorlogeSkynet/archey4#106]
**Describe the bug**

Line 278 reads:
```
// Use `sensors -A` to list the available chipsets on your system (e.g. `coretemp-isa-0000`, `acpitz-acpi-0`, ...).
```
For it to actually work it needs to be:
```
// Use `sensors -A` to list the available chipsets on your system (e.g. "coretemp-isa-0000", "acpitz-acpi-0", ...).
```
(Note the double quotes around the chipset names)

 This may be a stupid thing but it gave this non-programmer no end of trouble until I tried double quotes out of desperation. If this is something everyone else already understands then please ignore my ignorance.

**Comment by HorlogeSkynet** [comment]
Hey @fyrefiend ! Good catch, it's true JSON can be misleading if you haven't yet encountered every subtleties of it. There maybe are also too many back-quotes in this document 🙄
This is fixed, thanks for reporting it, bye 👋
