### ISSUE TITLE
[FEATURE] Change the Color from the Output

### ISSUE THREAD

**Issue by mrcsdl** [HorlogeSkynet/archey4#109]
**Describe the solution you'd like**

The possibility to adjust the color of the font of the output. Maybe in the Config file with hex color codes or something like that.
Something like
Default 
[RED]Hostname: [White]Homeserver
Custom
[Cyan]Hostname: [Yellow]Homeserver

**Comment by HorlogeSkynet** [comment]
Hi @mrcsdl

Entries color is currently being "inherited" from logo (the "first" one of the colors palette). May I assume you _only_ want to override this one, and not logo ones ?
If so, yes it could be achieved from configuration.

I have one more question though : how are we supposed to handle `OS-RELEASE`'s [`ANSI_COLOR`](https://www.freedesktop.org/software/systemd/man/os-release.html#ANSI_COLOR=) with such a new setting ?
(At the moment, this setting overrides the whole packaged colors palette, so logo **and** entries colors)

* Proposal 1 : new color setting overrides `ANSI_COLOR` globally (logo + entries)
* Proposal 2 : new color setting only overrides entries color (logo color would honor `ANSI_COLOR`, and entries color would honor new setting)

What do you think about this ?

Feel free to tell me I misunderstand your feature request.
Bye :wave:

**Comment by mrcsdl** [comment]
Proposal sounds awesome that's actually what I mean. 

I just want to customize it a bit. That it matches to the rest of my bash

**Comment by HorlogeSkynet** [comment]
Hey @mrcsdl, please see #110 and tell me whether the implementation fits your needs !
Closing here as PR is on its way.

**Comment by mrcsdl** [comment]
what type of imput ill need to do there iam a bit confused :D

"entries_color": "0,255,255",
this is not working but maybe its the wrong syntax right?

**Comment by HorlogeSkynet** [comment]
Have you correctly checked out the branch proposed in #110 locally ? It will only work there.
Separator is `;` and not `,`. Take a look to the URL available in README comment just above `entries_color`, it explains which values are expected 😇

**Comment by HorlogeSkynet** [comment]
Hey @mrcsdl, this feature has just been released as v4.13.4 ! Bye :pray:
