### ISSUE TITLE
[BUG]: In a WSL environment, Ubuntu is reported as Windows

### ISSUE THREAD

**Issue by x0341** [HorlogeSkynet/archey4#118]
**Describe the bug**
In a WSL environment, Ubuntu (or kali for example) is reported as Windows OS.

**Expected behavior**
same as neofetch or screenfetch reporting

**Screenshots**
![image](https://user-images.githubusercontent.com/1771943/190370037-e37ed221-7f18-4f35-96e5-fb0a9a769f9f.png)

![image](https://user-images.githubusercontent.com/1771943/190370672-93a64e21-a6fe-4d34-b006-62f38f098ad4.png)

**Environment**
 - Version used (4.Y.Z) : 
 - Method of installation (distribution package, PyPI, Homebrew, sources) : pip3 install archey4
 - Hardware type (laptop, server, Raspberry, hyper-visor) : laptop - WSL 2.0 environment with Ubuntu (or Kali)
 - Python version (3.Y.Z) :  3
 - Operating system and version : WSL 2.0 environment with Ubuntu (or Kali); Ubuntu 20
 - Graphical environment name and version : 
 - Connectivity (off-line, LAN only, Internet access) : 

**Additional context**

**Comment by HorlogeSkynet** [comment]
Hey @x0341, from an Archey point of view, I sincerely don't know whether it's a bug or a feature.
Since #16, WSL detection is performed using a "mark" on the kernel release string.

I'll refer to @Si13n7 on this 😇

**Comment by HorlogeSkynet** [comment]
So I agree with you, WSL here acts as a "virtualization method", not the distribution we want to show the logo of.

Unless @Si13n7 is strongly opposed to this, I'll drop this behavior and move kernel release string matching as a trivial WSL detection case under the `Model` entry, for the v4.14.0.0 :pray:

**Comment by HorlogeSkynet** [comment]
Released today as v4.14.0.0 :pray:
