### ISSUE TITLE
CPU not detected 

### ISSUE THREAD

**Issue by RobotsAreCrazy** [HorlogeSkynet/archey4#127]
CPU not being detected by archey.

On Debian bookworm arm64 (pi4)

Installed with sudo pip3 install archey4

Installed lm-sensors with sudo apt install lm-sensors

Not sure what else to install as have went through the dependency list?

**Comment by HorlogeSkynet** [comment]
Hi @RobotsAreCrazy,

Please next time fill the issue template in 🙃

Could you attach the output of `lscpu` and `cat /proc/cpuinfo` here ?

Thanks, bye 🙏

**Comment by RobotsAreCrazy** [comment]
Architecture:            aarch64
  CPU op-mode(s):        32-bit, 64-bit
  Byte Order:            Little Endian
CPU(s):                  4
  On-line CPU(s) list:   0-3
Vendor ID:               ARM
  Model name:            Cortex-A72
    Model:               3
    Thread(s) per core:  1
    Core(s) per cluster: 4
    Socket(s):           -
    Cluster(s):          1
    Stepping:            r0p3
    CPU(s) scaling MHz:  33%
    CPU max MHz:         1800.0000
    CPU min MHz:         600.0000
    BogoMIPS:            108.00
    Flags:               fp asimd evtstrm crc32 cpuid
Caches (sum of all):
  L1d:                   128 KiB (4 instances)
  L1i:                   192 KiB (4 instances)
  L2:                    1 MiB (1 instance)
Vulnerabilities:
  Itlb multihit:         Not affected
  L1tf:                  Not affected
  Mds:                   Not affected
  Meltdown:              Not affected
  Mmio stale data:       Not affected
  Retbleed:              Not affected
  Spec store bypass:     Vulnerable
  Spectre v1:            Mitigation; __user pointer sanitization
  Spectre v2:            Vulnerable
  Srbds:                 Not affected
  Tsx async abort:       Not affected

**Comment by RobotsAreCrazy** [comment]
Architecture:            aarch64
bhadmin@pi-srv:~ $ cat /proc/cpuinfo
processor       : 0
BogoMIPS        : 108.00
Features        : fp asimd evtstrm crc32 cpuid
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd08
CPU revision    : 3
processor       : 1
BogoMIPS        : 108.00
Features        : fp asimd evtstrm crc32 cpuid
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd08
CPU revision    : 3
processor       : 2
BogoMIPS        : 108.00
Features        : fp asimd evtstrm crc32 cpuid
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd08
CPU revision    : 3
processor       : 3
BogoMIPS        : 108.00
Features        : fp asimd evtstrm crc32 cpuid
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd08
CPU revision    : 3
Hardware        : BCM2835
Revision        : d03114
Serial          : 10000000e2761379
Model           : Raspberry Pi 4 Model B Rev 1.4

**Comment by RobotsAreCrazy** [comment]
> Hi @RobotsAreCrazy,
> 
> Please next time fill the issue template in 🙃
> 
> Could you attach the output of `lscpu` and `cat /proc/cpuinfo` here ?
> 
> Thanks, bye 🙏

Done 👍 Thanks
