### ISSUE TITLE
[BUG] uptime: /dev/ttys010: No such file or directory

### ISSUE THREAD

**Issue by MilesTEG1** [HorlogeSkynet/archey4#132]
**Describe the bug**
When launching archey, this message is shown at the very beginning output:
```
uptime: /dev/ttys010: No such file or directory
```

**Expected behavior**
Not show this error.

**Screenshots**
![image](https://user-images.githubusercontent.com/29298312/234201100-3cb59bd5-154c-4d7a-8dd1-40b46bee52d1.png)

**Environment**

 - Version used (4.X.Y.Z) : 4.14.1.0
 - Method of installation (distribution package, PyPI, Homebrew, sources) : homebrew
 - Hardware type (laptop, server, Raspberry, hyper-visor) : Macbook Air M2
 - Python version (3.Y.Z) : Python 3.11.3
 - Operating system and version : macOS Ventura 13.3.1 (22E261)
 - Graphical environment name and version : --
 - Connectivity (off-line, LAN only, Internet access) : LAN/Wifi/Internet

**Additional context**

**Custom configuration**

<details><summary>Custom configuration</summary>
<p>

```json
{
	"allow_overriding": true,
	"parallel_loading": true,
	"suppress_warnings": false,
	"entries_color": "",
	"honor_ansi_color": true,
	"logo_style": "retro",
	"entries": [
		{ "type": "User" },
		{ "type": "Hostname" },
		{ "type": "Model" },
		{ "type": "Distro" },
		{
			"type": "Kernel",
			"check_version": false
		},
		{ "type": "Uptime" },
		{
			"type": "LoadAverage",
			"decimal_places": 2,
			"warning_threshold": 1.0,
			"danger_threshold": 2.0
		},
		{ "type": "Processes" },
		{ "type": "WindowManager" },
		{ "type": "DesktopEnvironment" },
		{ "type": "Shell" },
		{
			"type": "Terminal",
			"use_unicode": true
		},
		{ "type": "Packages" },
		{
			"type": "Temperature",
			"char_before_unit": " ",
			"sensors_chipsets": [],
			"sensors_excluded_subfeatures": [],
			"use_fahrenheit": false
		},
		{
			"type": "CPU",
			"one_line": false,
			"show_cores": true
		},
		{
			"type": "GPU",
			"one_line": false,
			"max_count": 2
		},
		{
			"type": "RAM",
			"warning_use_percent": 33.3,
			"danger_use_percent": 66.7
		},
		{
			"type": "Disk",
			"show_filesystems": ["local"],
			"combine_total": true,
			"disk_labels": null,
			"hide_entry_name": null,
			"warning_use_percent": 50,
			"danger_use_percent": 75
		},
		{
			"type": "LAN_IP",
			"one_line": true,
			"max_count": 2,
			"show_global": false,
			"ipv6_support": false
		},
		{
			"type": "WAN_IP",
			"one_line": true,
			"ipv4": {
				"dns_query": "myip.opendns.com",
				"dns_resolver": "resolver1.opendns.com",
				"dns_timeout": 1,
				"http_url": "https://v4.ident.me/",
				"http_timeout": 1
			},
			"ipv6": {
				"dns_query": "myip.opendns.com",
				"dns_resolver": "resolver1.opendns.com",
				"dns_timeout": 1,
				"http_url": "https://v6.ident.me/",
				"http_timeout": 1
			}
		}
	],
	"default_strings": {
		"latest": "latest",
		"available": "available",
		"no_address": "No Address",
		"not_detected": "Not detected",
		"virtual_environment": "Virtual Environment"
	}
}
```

</p>
</details>

**Comment by ingrinder** [comment]
This appears to be a bug in macOS itself:

https://apple.stackexchange.com/questions/383653/why-does-uptime-want-dev-ttys021-no-such-file-or-directory
https://apple.stackexchange.com/questions/85520/uptime-dev-ttys003-no-such-file-or-directory

@HorlogeSkynet is this something we should try to hide from the user as a workaround?

**Comment by HorlogeSkynet** [comment]
Interesting, thanks for digging this up !
Maybe we can catch STDERR output and emit a warning using the entry logger, as done for `Tenperature` and `lm_sensors` errors ?
Using a configuration option already existing, one could easily silence those.

Tell me what you think about it 🙂

**Comment by HorlogeSkynet** [comment]
Closing here in favor of #133.
