### ISSUE TITLE
[FEATURE] Support wayland compositors in WindowManager and DesktopEnvironment modules

### ISSUE THREAD

**Issue by Nagefire** [HorlogeSkynet/archey4#151]
Please add detection for common wayland compositors (sway, wayfire, hyprland) in the window manager and desktop environment modules. A possible enhancement is to fallback to the environment variable `XDG_SESSION_DESKTOP`, which should be set by wayland compositors and X11 DEs alike.

**Comment by HorlogeSkynet** [comment]
Hi @Nagefire, could you please tell us whether #152 (RFC) corresponds to an implementation supporting Wayland ? :slightly_smiling_face:
Thanks, bye :wave:

**Comment by HorlogeSkynet** [comment]
Closing here, see #152.
