### ISSUE TITLE
Missing info using Raspberry Pi 5

### ISSUE THREAD

**Issue by MatsA** [HorlogeSkynet/archey4#156]
Nice application, but as said miss som info.
Thanks Mats

![Skärmavbild 2024-08-13 kl  22 54 57](https://github.com/user-attachments/assets/ab90e591-b611-4a3f-89dd-3054aeb69a83)

**Comment by HorlogeSkynet** [comment]
Thanks for your message.

Could you provide us the content of your `/proc/cpuinfo` ? It seems Pi detection is broken for 5 revision.

As for the `GPU` entry, there is ongoing #130 on the matter (and we're definitely interested in `/proc/modules` content !).

Thanks, bye 👋

**Comment by MatsA** [comment]
Hi !
Please find the requested info below

/Mats

pi@test:~ $ cat  /proc/cpuinfo
processor	: 0
BogoMIPS	: 108.00
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm lrcpc dcpop asimddp
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x4
CPU part	: 0xd0b
CPU revision	: 1

processor	: 1
BogoMIPS	: 108.00
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm lrcpc dcpop asimddp
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x4
CPU part	: 0xd0b
CPU revision	: 1

processor	: 2
BogoMIPS	: 108.00
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm lrcpc dcpop asimddp
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x4
CPU part	: 0xd0b
CPU revision	: 1

processor	: 3
BogoMIPS	: 108.00
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm lrcpc dcpop asimddp
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x4
CPU part	: 0xd0b
CPU revision	: 1

Revision	: c04170
Serial		: fc7b7a46275aa0f5
Model		: Raspberry Pi 5 Model B Rev 1.0

**Comment by MatsA** [comment]
pi@test:~ $ cat /proc/modules
rfcomm 81920 4 - Live 0x0000000000000000
snd_seq_dummy 49152 0 - Live 0x0000000000000000
snd_hrtimer 49152 1 - Live 0x0000000000000000
snd_seq 98304 7 snd_seq_dummy, Live 0x0000000000000000
snd_seq_device 49152 1 snd_seq, Live 0x0000000000000000
algif_hash 49152 1 - Live 0x0000000000000000
algif_skcipher 49152 1 - Live 0x0000000000000000
af_alg 49152 6 algif_hash,algif_skcipher, Live 0x0000000000000000
bnep 49152 2 - Live 0x0000000000000000
binfmt_misc 49152 1 - Live 0x0000000000000000
brcmfmac_wcc 49152 0 - Live 0x0000000000000000
brcmfmac 360448 1 brcmfmac_wcc, Live 0x0000000000000000
hci_uart 65536 0 - Live 0x0000000000000000
btbcm 49152 1 hci_uart, Live 0x0000000000000000
aes_ce_blk 49152 4 - Live 0x0000000000000000
aes_ce_cipher 49152 1 aes_ce_blk, Live 0x0000000000000000
bluetooth 622592 33 rfcomm,bnep,hci_uart,btbcm, Live 0x0000000000000000
rpivid_hevc 65536 0 - Live 0x0000000000000000 (C)
brcmutil 49152 1 brcmfmac, Live 0x0000000000000000
ghash_ce 49152 0 - Live 0x0000000000000000
v4l2_mem2mem 65536 1 rpivid_hevc, Live 0x0000000000000000
gf128mul 49152 1 ghash_ce, Live 0x0000000000000000
pisp_be 49152 0 - Live 0x0000000000000000
sha2_ce 49152 0 - Live 0x0000000000000000
sha256_arm64 49152 1 sha2_ce, Live 0x0000000000000000
sha1_ce 49152 0 - Live 0x0000000000000000
videobuf2_dma_contig 49152 2 rpivid_hevc,pisp_be, Live 0x0000000000000000
cfg80211 1032192 1 brcmfmac, Live 0x0000000000000000
ecdh_generic 49152 2 bluetooth, Live 0x0000000000000000
videobuf2_memops 49152 1 videobuf2_dma_contig, Live 0x0000000000000000
videobuf2_v4l2 49152 3 rpivid_hevc,v4l2_mem2mem,pisp_be, Live 0x0000000000000000
ecc 65536 1 ecdh_generic, Live 0x0000000000000000
raspberrypi_hwmon 49152 0 - Live 0x0000000000000000
libaes 49152 4 aes_ce_blk,aes_ce_cipher,bluetooth,ghash_ce, Live 0x0000000000000000
videodev 344064 4 rpivid_hevc,v4l2_mem2mem,pisp_be,videobuf2_v4l2, Live 0x0000000000000000
rfkill 49152 6 bluetooth,cfg80211, Live 0x0000000000000000
videobuf2_common 98304 6 rpivid_hevc,v4l2_mem2mem,pisp_be,videobuf2_dma_contig,videobuf2_memops,videobuf2_v4l2, Live 0x0000000000000000
mc 81920 6 rpivid_hevc,v4l2_mem2mem,pisp_be,videobuf2_v4l2,videodev,videobuf2_common, Live 0x0000000000000000
raspberrypi_gpiomem 49152 0 - Live 0x0000000000000000
rp1_adc 49152 0 - Live 0x0000000000000000
nvmem_rmem 49152 0 - Live 0x0000000000000000
sg 65536 0 - Live 0x0000000000000000
uio_pdrv_genirq 49152 0 - Live 0x0000000000000000
uio 49152 1 uio_pdrv_genirq, Live 0x0000000000000000
fuse 147456 5 - Live 0x0000000000000000
dm_mod 163840 0 - Live 0x0000000000000000
ip_tables 65536 0 - Live 0x0000000000000000
x_tables 81920 1 ip_tables, Live 0x0000000000000000
ipv6 589824 48 [permanent], Live 0x0000000000000000
spidev 49152 0 - Live 0x0000000000000000
vc4 409600 4 - Live 0x0000000000000000
snd_soc_hdmi_codec 49152 2 - Live 0x0000000000000000
drm_display_helper 49152 1 vc4, Live 0x0000000000000000
cec 65536 1 vc4, Live 0x0000000000000000
drm_dma_helper 49152 2 vc4, Live 0x0000000000000000
drm_kms_helper 262144 2 vc4,drm_dma_helper, Live 0x0000000000000000
snd_soc_core 327680 2 vc4,snd_soc_hdmi_codec, Live 0x0000000000000000
snd_compress 49152 1 snd_soc_core, Live 0x0000000000000000
snd_pcm_dmaengine 49152 1 snd_soc_core, Live 0x0000000000000000
v3d 114688 0 - Live 0x0000000000000000
gpu_sched 98304 1 v3d, Live 0x0000000000000000
snd_pcm 163840 4 snd_soc_hdmi_codec,snd_soc_core,snd_compress,snd_pcm_dmaengine, Live 0x0000000000000000
snd_timer 65536 3 snd_hrtimer,snd_seq,snd_pcm, Live 0x0000000000000000
drm_shmem_helper 49152 1 v3d, Live 0x0000000000000000
i2c_brcmstb 49152 0 - Live 0x0000000000000000
spi_bcm2835 49152 0 - Live 0x0000000000000000
snd 147456 9 snd_seq,snd_seq_device,snd_soc_hdmi_codec,snd_soc_core,snd_compress,snd_pcm,snd_timer, Live 0x0000000000000000
gpio_keys 49152 0 - Live 0x0000000000000000
drm 720896 8 vc4,drm_display_helper,drm_dma_helper,drm_kms_helper,v3d,gpu_sched,drm_shmem_helper, Live 0x0000000000000000
drm_panel_orientation_quirks 49152 1 drm, Live 0x0000000000000000
backlight 49152 2 drm_kms_helper,drm, Live 0x0000000000000000

**Comment by HorlogeSkynet** [comment]
Many thanks !

So it appears `/proc/cpuinfo` now directly specifies `Model : [...]` that we could parse for `CPU` entry. And for `GPU` I'll try to come up with an algorithm matching the correct VideoCore chipset for each Pi board (if possible).

Bye :wave:

**Comment by HorlogeSkynet** [comment]
Please see [7471de1](https://github.com/HorlogeSkynet/archey4/commit/7471de13fffa1e13af798630dd3c73493360aa03) for `CPU`.
I'm closing here and leave #130 which tracks `GPU` entry support for Pi boards.

Thanks again, bye :wave:
