### ISSUE TITLE
Strange behavior related to entry names

### ISSUE THREAD

**Issue by JFFWhiteside** [HorlogeSkynet/archey4#160]
Installed archey4 for debian and in the config.json file it looks normal but when I  launch a terminal emulator all the entries will say something like :
ruemUser
ruemHostname
ruemModel

and so on..

I can't tell what to edit in my config.json that will make it display normally. In fact I have not even edited it yet...

![Screenshot_20241125_154717](https://github.com/user-attachments/assets/8aadef10-1fdb-4410-8ba7-20221d8d2503)

**Comment by HorlogeSkynet** [comment]
Hello @JFFWhiteside, it's indeed a strange behavior. Do you use RubyEmacs ? Could you give more details about your environment ? Mostly environment variables (with redacted sensitive information) and terminal emulator.
Thanks, bye 👋

**Comment by HorlogeSkynet** [comment]
If possible, could you also include the content of your `/etc/os-release` file ? :slightly_frowning_face: 
Thanks :pray:

**Comment by JFFWhiteside** [comment]
yeah let me get back to you once i can get to my pc!

thanks for the help,
j

Sent from Proton Mail Android

-------- Original Message --------

**Comment by JFFWhiteside** [comment]
Hello again,

**os-release contents​​**
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

​**env-variables**
HOME=/home/user
LANG=en_US.UTF-8
LOGNAME=user
PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
SHELL=/bin/bash
SYSTEMD_EXEC_PID=1296
USER=user
XDG_RUNTIME_DIR=/run/user/1000
GTK_MODULES=gail:atk-bridge
QT_ACCESSIBILITY=1
QTWEBENGINE_DICTIONARIES_PATH=/usr/share/hunspell-bdic/
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
DESKTOP_SESSION=plasma
DISPLAY=:0
GPG_AGENT_INFO=/run/user/1000/gnupg/S.gpg-agent:0:1
GTK2_RC_FILES=/etc/gtk-2.0/gtkrc:/home/user/.gtkrc-2.0:/home/user/.config/gtkrc-2.0
GTK_RC_FILES=/etc/gtk/gtkrc:/home/user/.gtkrc:/home/user/.config/gtkrc
KDE_APPLICATIONS_AS_SCOPE=1
KDE_FULL_SESSION=true
KDE_SESSION_UID=1000
KDE_SESSION_VERSION=5
PAM_KWALLET5_LOGIN=/run/user/1000/kwallet5.socket
PWD=/home/user
QT_AUTO_SCREEN_SCALE_FACTOR=0
SESSION_MANAGER=local/lildebbian:@/tmp/.ICE-unix/1418,unix/lildebbian:/tmp/.ICE-unix/1418

My terminal emulator is KDE Konsole
I also haven't changed the config files either...

Cheers,
-J

**Comment by HorlogeSkynet** [comment]
Sorry for the delay @JFFWhiteside :pray:

So the debug isn't straightforward for me here. If sources haven't been altered, I really wonder what could cause this.
Although, could you try running `NO_COLOR=1 archey` and/or `archey -jj` in order for us to check whether it's a rendering issue, or somehow another internal one.

Thanks ! Bye :wave:

**Comment by ingrinder** [comment]
Hi @JFFWhiteside (and hi @HorlogeSkynet!),

I've also had a quick look into this and have some other questions that might help to narrow it down a little:-
* Do you happen to have any other file called `config.json` in your home directory?
* What Python version do you have installed? (`python --version`)
* How did you install Archey? (pip install, deb file, cloning git master etc)

The only pathway I can see for this occurring is via an `entries_color` being set to something invalid via configuration (e.g. any letter except `m` followed by `rue`: such as `rrue`) as the logo and the entry name text is coloured correctly. I tested on a fresh Debian VM installing via the deb file, and couldn't reproduce unless I set an invalid configuration in this way. It could be coming from the entry name itself but the invalid colour would explain the trailing `m`.

Along with the suggestions from @HorlogeSkynet would you also be able to try setting `"entries_color": "0;m"` in your configuration and testing whether this changes your output?

Hope we can get to the bottom of this!

Cheers,
Michael

**Comment by JFFWhiteside** [comment]
The issue seems to have been fixed!
I have python3.11 and installed via deb file...

I think by setting "entries_color": to "0;" (no "m") it now displays normally.

thanks for the help!
-J

**Comment by ingrinder** [comment]
Indeed, "0;" will workaround the issue but ideally we need to fix the issue so it doesn't occur in the first place. Was there any extra gibberish other than the previous "ruem" when you tried "0;m"? The other information will also be vital in figuring out where the problem is coming from so we can make sure no other users experience it!

**Comment by JFFWhiteside** [comment]
Sorry to get back to you so late!. As far as I know the only other thing that was displayed when I tried "0;m" was "m" so instead of seeing ruem in front of everything it was more like mUser, mHostname, mModel etc and so on. I really didn't change anything ( in my /etc/archey4/config.json) from when I did the initial install other than to set the "entries color": to true and then following your suggestion to "0;m" and eventually I just took the m out.

Hope any of that helps,

-J

**Comment by ingrinder** [comment]
> other than to set the "entries color": to true

Ah! That's the issue -- `entries_color` is interpreted as part of an escape code to set an exact colour (e.g. "0;32" would be green by substituting it into the output as `\x1b[0;32m`), so setting "true" causes it to emit `\x1b[truem` -- I'm guessing `t` terminates the escape code so the `ruem` is then emitted as plaintext. I *think* you should just be able to leave `entries_colour` blank and colour should work fine?

I see what's, the description in the readme describes the options in the comments above them rather than below but it's easy to mix them up. @HorlogeSkynet we should probably add newlines to space that out better or rearrange somehow (and perhaps validate the `entries_color` too) if that sounds good?

Glad to find the root cause! Hope the rest of your time using Archey is trouble-free :crossed_fingers: 

Cheers,
Michael

**Comment by HorlogeSkynet** [comment]
👌✅✅ @ingrinder, awewome suggestions.

**Comment by HorlogeSkynet** [comment]
Please see #161 ! Bye :wave:
