### ISSUE TITLE
Error when offline

### ISSUE THREAD

**Issue by Phoenix1747** [HorlogeSkynet/archey4#22]
## Expected behavior

Archey works flawlessly when online but fails when no internet connect is available.

## Current behavior

When I have no internet connection archey fails with the following error message:
```shell
Traceback (most recent call last):
  File "/usr/bin/archey4", line 936, in <module>
    output.append(key.name, key.value().value)
  File "/usr/bin/archey4", line 864, in __init__
    ], timeout=0.5, stderr=DEVNULL).decode().rstrip()
  File "/usr/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['dig', '+short', '-6', 'aaaa', 'myip.opendns.com', '@resolver1.ipv6-sandbox.opendns.com']' returned non-zero exit status 10.
```
I have the latest versions of bind-utils and python3 and I am experiencing this for the AUR and (this) git version.

## Your environment

* Version used (4.x.y) : latest (AUR)
* Operating System and version : Arch
* Connectivity (Off-line, LAN only, Internet access, ...) : on- and offline

**Comment by Phoenix1747** [comment]
Thanks 👍

**Comment by HorlogeSkynet** [comment]
Your welcome, this is something we broke during #15...
