### ISSUE TITLE
Consider using os-release instead of lsb_release

### ISSUE THREAD

**Issue by eli-schwartz** [HorlogeSkynet/archey4#36]
`lsb_release` is not always installed on a system, and requires running a subprocess in order to get information from it. The /etc/os-release file is required by any system booting with systemd, and encouraged as a distro-neutral and init-neutral identification method used by a number of non-systemd distros too. It's purpose is to replace the multitude of distro-specific foo-release files, as well as to provide something documented to be readable by any programming language without, say, depending on the implementation of a CLI command like lsb_release.

See for details:
http://0pointer.de/blog/projects/os-release
https://www.freedesktop.org/software/systemd/man/os-release.html

**Comment by HorlogeSkynet** [comment]
Hi,

This is something I already tried to implement in order to get rid of the `lsb-release` dependency but it appeared we would lose compatibility with dozens of distributions and OS versions not proposing this in the past.
Unless someone comes up with a BC implementation of this, we'll stick to how first releases of Archey worked, thus with this package.

BR

**Comment by eli-schwartz** [comment]
Why not fall back on lsb_release if os-release does not exist, thereby ensuring lsb_release is only a requirement on systems which do not have an os-release?

**Comment by HorlogeSkynet** [comment]
We could, someone has just to do it and update doc, tests & packages meta-data.

**Comment by HorlogeSkynet** [comment]
Okay, so now I remember why I abandoned this idea some months ago. If we drop lsb-release dependency, we actually have to build a parser-like for /etc/os-release, whereas the idea behind Archey is to keep the code simple and not extend it with dozens of lines doing a  job lsb-release has been built for.

**Comment by eli-schwartz** [comment]
It's a shell-compatible key="value" file format, the simple parser is:

```
import subprocess
subprocess.check_output("""sh -c '. /etc/os-release; echo "$NAME"'""", shell=True, universal_newlines=True).strip()
```

And the "complex" one is:

```
import shlex
with open("/etc/os-release") as f:
    OS_RELEASE = {}
    lexer = shlex.shlex(f, posix=True)
    lexer.whitespace_split = True
    for line in lexer:
        k, v = line.split('=', 1)
        OS_RELEASE[k] = v

print(OS_RELEASE['NAME'])
```

Or use https://pypi.org/project/distro/ (also used by pip) which conveniently falls back on lsb_release too.

**Comment by HorlogeSkynet** [comment]
By "parser-like" I was not only talking about a way of retrieving these data, but the postprocessing lsb-release does, and from what Archey has been built on.
The point is, if we build something on our own, I fear we would make lots of executions not working as expected, as currently. And I'm not referencing non-systemd devices only. This could concern dozens of specific cases, we would not been able to test against.

On the other hand, lsb-release is being used twice, and with two different invocations.
I don't know what the others think about this matter, but I personally rather leave this stuff under-the-hood.

**Comment by eli-schwartz** [comment]
That's because `python-distro` is indeed a package in community, not the AUR, and Arch policy is not to use python3- as package names. Note also that `python-pip` depends on the `distro` module too.

Also depending on lsb_release seems like a Debian packaging bug. They always provide the os-release file even though systemd is optional on Jessie.

Anyway, as I said, it's 8 lines to implement this yourself even if Debian does not package it. I guess you could provide an additional python3-distro .deb for Jessie users, though.

**Comment by HorlogeSkynet** [comment]
Agreed with the Debian-packaging bug, separate concern.

---

So I've run some more researches, below is what I'm considering today, after having discussed with you :

#### About Debian

Adding `python3-distro` module as an **optional dependency**. This way, Jessie users would still be able to install the package, and the BC implementation (see below) would make sense.
On their side, Stretch (and next) distribution users would be able to **install the `python3-distro` module**, and then `lsb-release` as it is required :stuck_out_tongue_winking_eye:

#### About Arch Linux

Adding `python-distro` as a **required dependency** (but is it possible as it comes from the Community repo ?), and **removing the `lsb-release` one**.
What I'm afraid of though : `python-distro` does not suggest `lsb-release` as an optional dependency on its own. Have you noticed ? Should we then ?

#### About PIP installation

Adding the `distro` module as a **required dependency**, and thus making `pip` install it if not already present (looks like `python[3]-distro` is not required by `python3-pip` on Debian...).

#### About Archey (intrinsically)

Implementing, in a BC way, information retrieval from **`distro` module** if available, and **falling back on `lsb_release`** if it is not (as done currently).

---

I am really looking forward not to having a piece of code (worst-ly) doing what is already done elsewhere... But I'm sure you guessed it.

What do you think about this ?
Thanks

PS : I know this is already a "long" topic, but @AdJaGu, @Si13n7 do you have any thoughts about this ?

**Comment by eli-schwartz** [comment]
If you add the dependency to setup.py then your console_scripts entry point will abort with a pkg_resources.DistributionNotFound error on systems where it is optional and not installed.

IMHO either:

1) reimplement the 8-line logic (falling back on lsb_release as currently done) yourself and do not depend on distro at all, in order to work on Jessie. In two years from now I guess you could switch to 2) as Jessie will be EOL.
2) remove lsb_release logic entirely, and depend on distro to do everything for you, then mark the .deb as too-new-for-Jessie, where users can install via pip instead.
3) same as 2) but provide an additional python3-distro .deb for Jessie users -- everyone else will have it installed either via pip or via pacman/rpm packaging


> looks like `python[3]-distro` is not required by `python3-pip` on Debian...

I guess they do not devendor pip, see https://github.com/pypa/pip/tree/master/src/pip/_vendor#debundling and [the Arch PKGBUILD for python-pip](https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/python-pip&id=96d1d6d73ef2836f49224e6c5d69a4d890662256#n24)

**Comment by HorlogeSkynet** [comment]
Sorry for bothering you (again) with my two cents but what about my previous "solution", considering that users going through `setuptools` would be somehow able to have `distro` ?

I mean :

1. If the user is going through `pip`, problem solved by automatic module installation (whatever the system is).
2. If the user is running Jessie and going through **package**, the `setup.py` is "ignored".
3. Each other environment : Either `distro` would be available or `setup.py` ignored by procedure too.

'hope my thought is clear...

If I'm wrong, I'd rather go with your `2`.

**Comment by eli-schwartz** [comment]
> If you add the dependency to setup.py then your console_scripts entry point will abort with a pkg_resources.DistributionNotFound error on systems where it is optional and not installed.

The setup.py is not ignored, it gets compiled into Python's site-packages as the egg-info which is then used by python ecosystem tools to check whether you've properly installed it. One of these ecosystem tools is the /usr/bin/archey4 script which is a setuptools wrapper script that first checks to see if all `/usr/lib/python${pythonver}/site-packages/${pkgname}-${version}-py${pythonver}.egg-info/requires.txt` dependencies are satisfied.

It would still work on Jessie... but only if the user installed distro on their own.

**Comment by HorlogeSkynet** [comment]
Okay thanks for your details, I think we will go with `2` then.
I just don't want to take this decision on my own, as we would somehow "break" an important use case of the main Debian distribution used currently...

Have a good evening

**Comment by HorlogeSkynet** [comment]
Closing here as #37 is now opened. See you on the other side.
