### ISSUE TITLE
Disk: reports incorrect information for tempfs and BTRFS

### ISSUE THREAD

**Issue by qx071** [HorlogeSkynet/archey4#42]
Disk utilisation and total includes tempfs when stored in RAM and duplicates btrfs subvolumes.

## Expected behavior
My system is installed on 11GB partition with /, /home, /swap, /var/log and /var/cache/pacman/pkg in separate subvolumes.  I would expect disk utilisation not to duplicate subvolume usage and exclude file systems in RAM (as Arch defines tempfs by default).

## Current behavior
archey4 reports 21GB used of 100GB for my 11GB partition.

The problem is the summing output from df which sums all tmpfs and btrfs resulting in excessive utilisation and space numbers.  

This is what "class disk" does:

```
[hali@Linux ~]$ df -Tlh -B GB --total -t ext4 -t ext3 -t ext2 -t reiserfs -t jfs -t zfs -t ntfs -t fat32 -t btrfs -t fuseblk -t xfs -t simfs -t tmpfs -t lxfs
Filesystem     Type  1GB-blocks  Used Available Use% Mounted on
run            tmpfs        9GB   1GB       9GB   1% /run
/dev/sda7      btrfs       11GB   4GB       8GB  33% /
tmpfs          tmpfs        9GB   1GB       9GB   2% /dev/shm
tmpfs          tmpfs        9GB   0GB       9GB   0% /sys/fs/cgroup
/dev/sda7      btrfs       11GB   4GB       8GB  33% /var/cache/pacman/pkg
/dev/sda7      btrfs       11GB   4GB       8GB  33% /var/log
/dev/sda7      btrfs       11GB   4GB       8GB  33% /var/swap
/dev/sda7      btrfs       11GB   4GB       8GB  33% /home
/dev/sda7      btrfs       11GB   4GB       8GB  33% /.snapshots
tmpfs          tmpfs        9GB   1GB       9GB   1% /tmp
tmpfs          tmpfs        2GB   1GB       2GB   1% /run/user/1000
total          -          100GB  21GB      79GB  21% -
[hali@Linux ~]$
```

While this is btrfs utilisation

```
[root@Linux hali]# btrfs filesystem usage /
Overall:
    Device size:		  10.00GiB
    Device allocated:		   4.27GiB
    Device unallocated:		   5.73GiB
    Device missing:		     0.00B
    Used:			   3.18GiB
    Free (estimated):		   6.67GiB	(min: 6.67GiB)
    Data ratio:			      1.00
    Metadata ratio:		      1.00
    Global reserve:		  16.00MiB	(used: 0.00B)

Data,single: Size:4.01GiB, Used:3.06GiB
   /dev/sda7	   4.01GiB

Metadata,single: Size:264.00MiB, Used:121.36MiB
   /dev/sda7	 264.00MiB

System,single: Size:4.00MiB, Used:16.00KiB
   /dev/sda7	   4.00MiB

Unallocated:
   /dev/sda7	   5.73GiB
[root@Linux hali]#
```
## Possible solution

Perhaps just show Root like archey3?

The 'btrfs fi usage' figure "Used:" of 3.18GB is the same as *one* instance of df figure for /dev/sda7 (although less than allocated).

## Your environment

```
[hali@Linux ~]$ archey4

               +                 User: hali
               #                 Hostname: Linux
              ###                Model: MacBookPro11,2
             #####               Distro: Arch Linux [x86_64]
             ######              Kernel: 5.0.7-arch1-1-ARCH
            ; #####;             Uptime: 2 minutes
           +##.#####             WindowManager: i3
          +##########            DesktopEnvironment: i3
         #############;          Shell: /bin/bash
        ###############+         Terminal: rxvt-unicode-256color ## ## ## ## ## ## ##
       #######   #######         Packages: 437
     .######;     ;###;`".       Temperature: 42.0 C (Max. 51.0 C)
    .#######;     ;#####.        CPU: Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    #########.   .########`      GPU: Intel Corporation Crystal Well Integrated...
   ######'           '######     RAM: 222 MB / 15947 MB
  ;####                 ####;    Disk: 21 GB / 100 GB
  ##'                     '##    LAN_IP: 192.168.1.19
 #'                         `#   WAN_IP: xxxxxxxxxxxx
```

/etc/fstab
```
LABEL=Linux             /                       btrfs   rw,relatime,compress=lzo,ssd,space_cache,subvolid=258,subvol=A1398_volume/arch                                  0 0
LABEL=Linux             /home                   btrfs   rw,relatime,compress=lzo,ssd,space_cache,subvolid=259,subvol=A1398_volume/home                                  0 0

# No snapshots
LABEL=Linux             /var/cache/pacman/pkg   btrfs   rw,relatime,compress=lzo,ssd,space_cache,subvolid=273,subvol=A1398_volume/var-cache-pacman-pkg                  0 0
LABEL=Linux             /var/log                btrfs   rw,relatime,compress=lzo,ssd,space_cache,subvolid=274,subvol=A1398_volume/var-log                               0 0
LABEL=Linux             /.snapshots             btrfs   rw,relatime,compress=lzo,ssd,space_cache,subvolid=260,subvol=A1398_volume/.snapshots                            0 0

LABEL=EFI               /boot                   vfat    rw,relatime,fmask=0022,dmask=0022,codepage=437,iocharset=iso8859-1,shortname=mixed,utf8,errors=remount-ro       0 2

# Swap
LABEL=Linux             /var/swap               btrfs   rw,relatime,ssd,space_cache,subvolid=272,subvol=A1398_volume/swap                                               0 0
/var/swap/swapfile      none                    swap    defaults 0 0
```
Subvolumes
```
[root@Arch-A1398 hali]# btrfs subvolume list /
ID 257 gen 1004 top level 5 path A1398_volume
ID 258 gen 995 top level 257 path arch
ID 259 gen 993 top level 257 path home
ID 260 gen 975 top level 257 path .snapshots
ID 262 gen 27 top level 258 path arch/var/lib/portables
ID 263 gen 28 top level 258 path arch/var/lib/machines
ID 266 gen 975 top level 259 path home/.snapshots
ID 272 gen 1002 top level 257 path swap
ID 273 gen 1003 top level 257 path var-cache-pacman-pkg
ID 274 gen 1004 top level 257 path var-log
```

**Comment by HorlogeSkynet** [comment]
Hi @qx071, thanks for reporting this.
You have a very particular setup that has never been tested previously.

So I guess you are describing two different issues here.

For the `tmpfs` one, as it is only located in **RAM**, I think it should not be part of the final **disk** usage computation. What do you think about that ?

About the `btrfs` one, I fear I don't know the particularity of the file system and its CLI tools enough to solve what you are pointing to.
But the workaround you propose would break setups with third mount points and external drives making part of the available storages (?).

Waiting for your input on this.
Would you want / be able to submit PR(s) for this ? Before or after the global rewrite being worked on currently (#41), as you prefer.

Bye :wave:

**Comment by qx071** [comment]
> You have a very particular setup that has never been tested previously.

OpenSUSE uses btrfs with [8 subvolumes](https://en.opensuse.org/SDB:BTRFS) by default so it isn't that weird a set-up.

> For the tmpfs one, as it is only located in RAM, I think it should not be part of the final disk usage computation. What do you think about that ?

I agree and removing tmpfs should be easy (just remove '-t tmpfs')  but I'm not sure how to deal with btrfs. 

The easiest would be to replace 'df -Tlh -B GB --total' with 'df / -Tlh --total' (selecting root and dropping the '-B G' which always rounds up).  I tried this and it works OK.

Like you say this would mean that secondary mounts, external drives etc would **not** be included in the total although note that at the moment btrfs on external drives will also show disk utilization (both disk size and disk used) multiplied by the number of subvolumes.  

If you wanted to show additional mount points and external drives etc  it would make it a whole lot more complex - ideally checking the filesystem type and use a different algorithm.  Perhaps manually accumulating totals from df rather than using '--total' would work and be close enough (read through all output and add to total only when mount point changes so there is only one instance for each */dev/sdXn*).  

I don't know how to program that though as I never wrote any python (nor used git actually).

**Comment by qx071** [comment]
was closed by mistake.

**Comment by HorlogeSkynet** [comment]
Thanks for your feedback. See my points below :

---

> OpenSUSE uses btrfs with 8 subvolumes by default so it isn't that weird a set-up.  

I mostly meant among Archey users, and didn't know about OpenSuse using it this way so, sorry, and glad to collect your advices in the future.

---

Okay for removing `tmpfs` then, and listing disk usage on `/`.  
It'd definitely be a breaking change, but from a _system_ point of view, local storage usages is more relevant than the external and network ones (@AdJaGu @Si13n7, it's open to suggestions over here too !).

> Note : [The _original_ version of Archey **didn't** specify a mounting point either](https://github.com/djmelik/archey/blob/master/archey#L228).

---

About the `-B GB` flag, I sadly didn't comment the change back in the past, but I think this was meant to avoid a mathematical conversion in Python, when usage (and/or maximum) sizes are too small (and are displayed in MB by `df`)...

---

Within some days / weeks I'll end up #41 and publish these changes afterwards, once the rewrite is done. Stay tuned :crossed_fingers:

Bye :wave:

**Comment by HorlogeSkynet** [comment]
Closing here as (WIP) PR is now on its way (#43).
