### ISSUE TITLE
Better temperature detection

### ISSUE THREAD

**Issue by EntityCuber** [HorlogeSkynet/archey4#45]
Temperature is not detected

Can you please fix this by adding more temperature detection methods or using lm-sensor

Is there any way to use grep and put it on there?

* Version used archey 4.6 
* laptop
* Operating system : Archlinux

**Comment by HorlogeSkynet** [comment]
Hey, could you first paste here the result of the command below please ?

```bash
cat /sys/class/thermal/thermal_zone*/temp
```

Thanks 👋

**Comment by EntityCuber** [comment]
zsh: no matches found: /sys/class/thermal/thermal_zone*/temp

I dont have any thermal_zone files

/sys/class/thermal/   < -  in this directory i have only 2 folders 'cooling_device1' and 'cooling_device2'

**Comment by HorlogeSkynet** [comment]
Well, that's interesting.
Could you tell us (if you don't mind) what kind of hardware you got (for future release notes, when this will be fixed) ?

Anyway, if you manage to get something with the `sensors` command, I will rework this entry logic by making it process such output.

Bye 👋

**Comment by EntityCuber** [comment]
CPU: AMD A9-9420 RADEON R5, 5 COMPUTE CORES 2C+3G
GPU: AMD R5

**Comment by HorlogeSkynet** [comment]
And what about the `Model` entry ? 😮

**Comment by EntityCuber** [comment]
> And what about the `Model` entry ? open_mouth

Model: 80XV

**Comment by EntityCuber** [comment]
sensors | grep -oP 'temp1:.*?\+\K[0-9.]+' | head -1

**Comment by HorlogeSkynet** [comment]
Thanks for your replies.
About `sensors`, I think I'll implement something like [this](https://git.forestier.app/HorlogeSkynet/SimpleConkyScript/src/branch/master/lua/system.lua#L43). It works well and allows an average computation _easily_.
I'll keep you posted, bye 👋

**Comment by HorlogeSkynet** [comment]
Closing here, as #47 is now on going.
