### ISSUE TITLE
bug?

### ISSUE THREAD

**Issue by batizisanya** [HorlogeSkynet/Archey4#5]
I isntalled, but not working. Debian 

root@madoka:~# archey
Traceback (most recent call last):
  File "/usr/bin/archey", line 597, in <module>
    output.output()
  File "/usr/bin/archey", line 398, in output
    print(logosDict[self.distribution].format(c=colorDict[self.distribution], r=results) + colorDict['clear'])
UnicodeEncodeError: 'ascii' codec can't encode character '\u2205' in position 557: ordinal not in range(128)

**Comment by AdJaGu** [comment]
Does adding `# -*- coding: utf-8 -*-` right after `#!/usr/bin/env python3` in the file archey fix this for you @batizisanya?

**Comment by batizisanya** [comment]
No, its shows she same error.

**Comment by AdJaGu** [comment]
Well, sorry that didn't help you @batizisanya. That was my only idea. I'm sure @HorlogeSkynet will be around with a fix soon.

**Comment by batizisanya** [comment]
No problem, and thank you for trying to help 👍

**Comment by HorlogeSkynet** [comment]
Hello @batizisanya,

I don't understand how this problem may appear there. Could you tell me exactly which variable with its content can't be printed in order to debut that ? 

Thanks !

**Comment by batizisanya** [comment]
I just downloaded your script and put to /usr/bin/archey. 
And when i wrote archey, than i got this error msg.

**Comment by HorlogeSkynet** [comment]
Oh okay, I'll start thinking about that tomorrow but I'm not sure I'd figure it out without your problem in front of me...

**Comment by HorlogeSkynet** [comment]
Hey,

So this is my idea (and only track yet) : You have a hostname or something like this with a special character, and Python couldn't decode it as well.
Can you check that ?

**Comment by batizisanya** [comment]
I use debian server. Without desktop environment.

**Comment by HorlogeSkynet** [comment]
Yeah okay so this is it... I'll do some searches, but right now, I dunno why you cannot print that 😂

**Comment by HorlogeSkynet** [comment]
---
I'm back there !

This should really not appear here ; It looks like you're using Python 2 or somehow the encoding is not correct for this character (and many others as you surely has understood).
So, I've got rid of them, and change these default strings. (b48a518744317341308b439accc1582aee8dd155)

If you're OK with that, close this one too 😉

Cya, and have a nice week 👋

**Comment by batizisanya** [comment]
WOW, thank you!  👍 
And also thx for the fast help.

Have a nice week, bye.
