### ISSUE TITLE
[FEATURE] Configuration option to rearrange modules.

### ISSUE THREAD

**Issue by ingrinder** [HorlogeSkynet/archey4#57]
**Is your feature request related to a problem? Please describe.**
I would like to be able to change the order that the modules are printed in.

**Describe the solution you'd like**
Make the configuration file be able to define the order in which modules are printed - perhaps following the order of an array?

**Describe alternatives you've considered**
Using archey3 😛 

**Additional context**
Not sure how doable this is, and would probably require a pretty big rewrite to achieve too... Would be really nice to have, though.

**Comment by HorlogeSkynet** [comment]
See #80, this feature will land in v4.9.0 with the new configuration layout 🎉
