### ISSUE TITLE
pkg_resources.DistributionNotFound: The 'archey4==4.7.0' distribution was not found and is required by the application

### ISSUE THREAD

**Issue by brilliant116** [HorlogeSkynet/archey4#59]
**Screenshots**

**Environment**
Please complete the following information.
 - Version used (4.Y.Z) : archey4-4.7.0-2.noarch.rpm
 - Method of installation (distribution package, PIP, sources) : dnf install
 - Hardware type (laptop, server, Raspberry, hyper-visor) : Virtual Box
 - Python version (3.Y.Z) : python 3.8.2
 - Operating system and version : Fedora 32
 - Graphical environment name and version : KDE Plasma 5.18
 - Connectivity (off-line, LAN only, Internet access) : Internet access

**Additional context**

First, I download the .rpm file, then install it

```
sudo dnf install ./archey4-4.7.0-2.noarch.rpm
```

when I type `archey` in terminal, I occured following output:

```
Traceback (most recent call last):
  File "/usr/bin/archey4", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3259, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3242, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3271, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 584, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 901, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 787, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'archey4==4.7.0' distribution was not found and is required by the application
```

Hope you can help me solve the problems

**Comment by HorlogeSkynet** [comment]
Hi, thanks for reporting ! I can reproduce it within a Fedora 31 environment (Python 3.7.1).
I've browsed the WWW for a long time, and couldn't really understand why we are getting this.
The package generated by FPM looks good to me, but I'm not an RPM expert, so I fear we will have to ask for external help, maybe @Xysto ?

I've also tried (without any success) a distribution-independant SetupTools upgrade with : `dnf install python3-pip && pip3 install -U setuptools`.

Bye, keep us posted if you got any news on your own :wave:

**Potential** related issues :
* pypa/setuptools#1495
* pypa/pip#2868
* <https://www.elastic.co/guide/en/elasticsearch/client/curator/current/entrypoint-fix.html>

**Comment by HorlogeSkynet** [comment]
Okay [got it](https://github.com/HorlogeSkynet/archey4/blob/1e04cc9d4fecbe8a103a86259a918cdd7f9d4eaa/packaging/build.sh#L64).  
We actually have to specify the Python version in the installation path, as : `/usr/lib/python3.{4,5,6,7,8}/site-packages` .
Debian implements [a nice trick](https://www.debian.org/doc/packaging-manuals/python-policy/ch-python.html#s-paths) avoiding maintainers to deal with this issue, so I have not noticed it before.

Some references :

* <https://leemendelowitz.github.io/blog/how-does-python-find-packages.html>
* <https://unix.stackexchange.com/questions/488135/how-to-build-an-rpm-package-for-python-app-that-works-in-fedora-28-and-29-which#>

---

So the question is : How do we "elegantly" support multiple CentOS / Fedora versions ?
I think about tweaking the `build.sh` script to deal with all of these versions.

@brilliant116, would `archey4-4.Y.0Z-R.el{5,6,7,8}.noarch` be sufficient from your point of view ?

> Note for Arch Linux : As it is a rolling distribution, building compatible packages is easy as specifying the latest stable Python version.

**Comment by HorlogeSkynet** [comment]
Update : I've dropped the `elX` and `fYY` ideas.
@brilliant116, could you please tell us what you think about #
60 ?

> Closing here as a linked PR is opened.

**Comment by brilliant116** [comment]
https://github.com/HorlogeSkynet/archey4/pull/60 The solution may be fine.

**Comment by HorlogeSkynet** [comment]
Hello @brilliant116, v4.7.1 is out, and new packages have been uploaded :ok_hand:

https://github.com/HorlogeSkynet/archey4/releases/tag/v4.7.1

Bye :wave:
