### ISSUE TITLE
compliant package naming

### ISSUE THREAD

**Issue by sylv3r** [HorlogeSkynet/archey4#6]
Hi,

I wanted to improve archey3 to my needs but then I first had a look on the many forks from the original archey and I found yours as the most advanced one.
I use Arch and I was surprised not to find your version in the AUR repository, so I'm preparing a package if that's ok for you (and that would be nice to make some .deb and .rpm too eventually).
Problem is, your repository naming doesn't fit well with the packaging naming convention.
Could you lowercase it to "archey4" so I can finish the PKGBUILD and propose you a pull request, please ?

**Comment by HorlogeSkynet** [comment]
Hello,

That's a great idea (I never prepared any package in my life so now you've got the reason why it's not in the AUR 😛).

I've just renamed this repo, I'll do the same in the README and the source another day (among other changes).

Bye 👋

**Comment by HorlogeSkynet** [comment]
See (1e017fbb2b1f06c1ff29e3c73faf6897fc92c720).

**Comment by HorlogeSkynet** [comment]
Salut Richard @sylv3r !

As-tu toujours prévu de mettre au point un PKGBUILD pour ce projet ?
Si oui, quelle devra être la procédure pour le soumettre sur le AUR ensuite, par exemple ?

Merci ! Bye 👋

**Comment by HorlogeSkynet** [comment]
Nervermind, je m'en suis occupé : https://aur.archlinux.org/packages/archey4/
