### ISSUE TITLE
[FEATURE] GPU support when multiple GPUs are present

### ISSUE THREAD

**Issue by ingrinder** [HorlogeSkynet/archey4#61]
**Is your feature request related to a problem? Please describe.**
Currently only one GPU appears in Archey's output. For example, my PC has a dedicated Nvidia GTX 970 + the integrated Intel UHD 630 GPU. When I run Archey, it displays `GPU: Intel Corporation UHD Graphics 630 (Desktop)`, with no mention of my Nvidia GPU.

**Describe the solution you'd like**
One of these would be ideal:
* Display both GPUs (this might be what someone with multiple discrete GPUs wants)
* Have the ability to display the GPU of my choice (i.e. the dedicated one in my case).

**Describe alternatives you've considered**
I could disable the integrated graphics, however I use it with IOMMU for virtual machines so I would prefer to keep it enabled and have the ability to display my dedicated GPU.

**Additional context**
The output of `lspci | egrep "3D|VGA|Display"` is:
```
00:02.0 Display controller: Intel Corporation UHD Graphics 630 (Desktop)
01:00.0 VGA compatible controller: NVIDIA Corporation GM204 [GeForce GTX 970] (rev a1)
```

**Comment by HorlogeSkynet** [comment]
Closing as #71 is now on its way.
