### ISSUE TITLE
[BUG] Doesn't fit terminal size

### ISSUE THREAD

**Issue by SomethingGeneric** [HorlogeSkynet/archey4#63]
**Describe the bug**
Some lines of archey system info wrap to next line on Ubuntu 20.04 80col x 24row

**Expected behavior**
Regular system info display

**Screenshots**
(note: "Reminders" is my own program. I'm talking about archey above it.)
![Screenshot from 2020-04-26 14-35-27](https://user-images.githubusercontent.com/12242178/80316427-c61b2500-87cb-11ea-8e23-210369715d38.png)

**Environment**

 - Version used (4.Y.Z) : 4.7.1
 - Method of installation (distribution package, PyPI, sources) : `.deb` package
 - Hardware type (laptop, server, Raspberry, hyper-visor) : Custom built desktop tower
 - Python version (3.Y.Z) : 3.8.2
 - Operating system and version : Ubuntu 20.04
 - Graphical environment name and version : Gnome 3.34 (I think, per Ubuntu "Software")
 - Connectivity (off-line, LAN only, Internet access) : Ethernet access

**Additional context**
Just installed 20.04 "the debian way" so maybe this is a OS issue, but I figured I'd report anyway.

**Comment by SomethingGeneric** [comment]
I just made 100% sure that my own program is not the issue. Still could potentially be any number of things w/ the new Ubuntu release.

**Comment by HorlogeSkynet** [comment]
Hi, thanks for your report !
It's actually a "known-bug", and "officially" since... [this morning](https://github.com/HorlogeSkynet/archey4/pull/58#issuecomment-619511992).

We'll be working on this soon, bye 👋

**Comment by ingrinder** [comment]
I've pushed some output changes I was working on yesterday to [rework/output](/HorlogeSkynet/archey4/tree/rework/output) which should enable the wrapping that @HorlogeSkynet mentioned in the comment this morning a lot easier - I believe it should now be possible to wrap to the terminal size reported by [`os.get_terminal_size`](https://docs.python.org/3/library/os.html#os.get_terminal_size). I'll let you know in a few minutes 😄

**Comment by SomethingGeneric** [comment]
@ingrinder glad to hear it!

**Comment by ingrinder** [comment]
@SomethingGeneric is this the behaviour you'd like? Here's how my output looks at 80x24 with commit e5dca9dbf85644fde197d4a66f90213c15c283a7 above.

![image](https://user-images.githubusercontent.com/12384431/80321777-6a728b00-880f-11ea-8938-7c64421e6e58.png)

I'm thinking it *could* be possible to wrap lines and display them underneath, but a lot harder, so if this truncation with a `...` is fine we can stick with that 😃

**Comment by SomethingGeneric** [comment]
@ingrinder that's perfect! I don't particularlly care myself about having my IP's show (since I know them), and that's much better than having the lines extend and cut stuff off.

**Comment by HorlogeSkynet** [comment]
Closing here as #64 is on its way. Will be reviewed soon 👌

**Comment by HorlogeSkynet** [comment]
Hey @SomethingGeneric ! Sorry for the delay, the patch is now available in the latest release :ok_hand:
