### ISSUE TITLE
[FEATURE] Better terminal detection

### ISSUE THREAD

**Issue by ingrinder** [HorlogeSkynet/archey4#65]
**Is your feature request related to a problem? Please describe.**
At the moment the detected terminal for xterm-compliant terminal emulators is always `xterm-256color`. It would be nice if this could display the *actual* terminal emulator in use, e.g. `Konsole`, `gnome-terminal`, `xterm`, `terminator`, `xfce4-terminal`, etc...

Ideas for implementing this are:
* Determine the terminal emulator based on parent processes of our process.
  * Could possibly require recursion (e.g. screen sessions)
  * Might not always give a desired result (SSH/mosh?)
* Use known environment variables to determine the terminal emulator
  * e.g. Konsole has `$KONSOLE_VERSION`, I imagine other terminal emulators also have similar environment variables.
  * Messy! Would require a big list of all possibilities... 😫 
* Use X11 to determine current active window (and therefore terminal emulator)
  * e.g. `xprop` tool.
  * Brings in another dependency...
  * Won't work if the terminal emulator opens in the background.
  * Also won't work on headless systems, or via SSH/mosh.
  * Wayland incompatible (e.g. Fedora)

**Comment by HorlogeSkynet** [comment]
Not very keen about 1 & 3, but I think we could easily implement 2 (with the current situation as a proper fallback).
We could rely on what Neofetch and/or Screenfetch do too, and in the future, one will be 1-PR away from having its-wonderful-terminal-emulator added to the list, and thus supported (as how we currently handle DE & WM) 👌

**Comment by HorlogeSkynet** [comment]
Closing here as #72 is on its way.
