### ISSUE TITLE
[QUESTION] [FEATURE] Multithreading?

### ISSUE THREAD

**Issue by ingrinder** [HorlogeSkynet/archey4#68]
**Is your feature request related to a problem? Please describe.**
Maybe this is overkill, but on my system Archey typically runs in around 300-350ms. Some profiling reveals that quite a lot of this is waiting on I/O from commands, files, or internet requests.

I wondered whether multithreading would help make some good use of this CPU wait time, and it does! I pushed a commit to [ingrinder/archey4/optimisation](https://github.com/HorlogeSkynet/archey4/compare/master...ingrinder:optimisation) implementing multithreading with the builtin `concurrent.futures` library, and I get runtimes of around 130-150ms (<100ms with WAN_IP disabled). Since I have archey in my `.bashrc` this is quite a noticeable difference 😃

**Additional context**
Things to consider:
* 👍 Quicker execution time!
* 👍 Spawning threads is lightweight compared to processes.
* 👍 Due to our new `Output` format we get to keep the same order-of-entries even if they are instantiated asynchronously(-ish).
* 👎 Profiling is now less accurate since we end up just profiling the thread pool.
* 👎 It's possible Python doesn't support multithreading on all platforms? For example, I know multi*processing* isn't supported on Android, but multi*threading* appears to be. Not sure where I can find more info on this? Surely most platforms implement threads... right?!

Perhaps given the above downsides, it could be a configurable option? This may give the benefit of compatibility and speed 🚀. Let me know what you think about this anyway.

**Comment by HorlogeSkynet** [comment]
Yep, as entries are completely independent, it was actually a very long-term plan to add support for parallelism.
Now they actually inherit from `Entry`, maybe we can use the abstraction to handle worker pool from there (based on configuration as you proposed) ?

Anyway, a WIP PR will be appreciated... as always 💯

**Comment by HorlogeSkynet** [comment]
Closing here as #74 is on its way.
