### ISSUE TITLE
Wifi IP listed as LAN IP - No LAN on laptop

### ISSUE THREAD

**Issue by 0mni** [HorlogeSkynet/archey4#7]
```
╭─me@my-pc ~/build/Archey4  ‹master› 
╰─$ archey

 $$$$$$$$$$$$$$$$  $$$$$$$   User: me
 M77777777777777M  M77777M   Hostname: my-pc
 M77777777777777M  M77777M   Model: MacBookAir4,2
 M77777MMMMMMMMMM  M77777M   Distro: "Manjaro Linux" x86_64
 M77777M           M77777M   Kernel: 4.12.8-1-MANJARO
 M77777M  $$$$$$$  M77777M   Uptime: 11 hours and 36 minutes
 MMMMMMM  M77777M  M77777M   WindowManager: i3
          M77777M  M77777M   DesktopEnvironment: i3
 $$$$$$$  M77777M  M77777M   Shell: /usr/bin/zsh
 M77777M  M77777M  M77777M   Terminal: xterm-256color
 M77777M  M77777M  M77777M   Packages: 882
 M77777M  M77777M  M77777M   CPU: Intel(R) Core(TM) i7-2677M CPU @ 1.80GHz
 M77777M  M77777M  M77777M   GPU: Intel Corporation 2nd Generation Core [...]
 M77777M  M77777M  M77777M   RAM: 1095 MB / 3868 MB
 M77777M  M77777M  M77777M   Disk: 13 GB / 162 GB
 M77777M  M77777M  M77777M   LAN_IP: xx.xx.xx.xx
 M77777M  M77777M  M77777M   WAN_IP: No Address
 MMMMMMM  MMMMMMM  MMMMMMM   
```

**Comment by HorlogeSkynet** [comment]
Hello,

With this title issue I assume it's the expected behaviour, as long as you are connected to a Local Area Network through your WiFi.

Tell me if I misunderstood what you meant

**Comment by normcyr** [comment]
To add to @HorlogeSkynet comment: **LAN** stands for **L**ocal **A**rea **N**etwork, whereas **WAN** stands for **W**ide **A**rea **N**etwork. Therefore, archey4 will return your LAN IP address(es) in the LAN field hence explaining why you see your wifi IP ("WLAN"). 

If your system is connected to both a wired and a wireless connection to your local network, you will see both IP addresses being displayed.

**Comment by 0mni** [comment]
Thanks for clearing it up, would it be possible to have LAN/WIFI seperated?  As a feature request :)

**Comment by HorlogeSkynet** [comment]
Hi again,

I don't think there is an easy way to do this, as long as `hostname -I` returns just the local IP addresses, regardless the hardware interface types...
We would be able to compute something with the `ip` command, but we'd lose the interest of using `hostname` (a lot faster) on most of the devices.

Bye

**Comment by HorlogeSkynet** [comment]
## Expected Behavior



## Current Behavior



## Possible Solution



## Your Environment

* Version used (4.x.y) : 
* Hardware type (Laptop, Server, Raspberry, ...) : 
* Operating System and version : 
* Environment name and version : 
* Connectivity (Off-line, LAN only, Internet access, ...) :
