### ISSUE TITLE
[FEATURE] Add option to disable OpenDNS lookups

### ISSUE THREAD

**Issue by mrzv** [HorlogeSkynet/archey4#81]
**Is your feature request related to a problem? Please describe.**
For some reason my employer blocks OpenDNS lookups, so these always timeout causing substantial delays.

**Describe the solution you'd like**
An option that skips OpenDNS lookup and goes straight for ident.me would solve this problem.

**Comment by HorlogeSkynet** [comment]
Hey, I planned to rework `WAN_IP` once #80 is merged, I'll try to add such a way to configure this behavior at the same time in v4.8.0 too.
Stay put, see you :wave:

**Comment by HorlogeSkynet** [comment]
Hey @mrzv !
Eventually, `WAN_IP` got reworked. May I ask you to you review or even try #89 out ?
As it implies a configuration layout rework too (see #80), you may want to fetch and tweak the [new configuration file from the branch itself](https://github.com/HorlogeSkynet/archey4/blob/feature/wan_ip_configurable_resolvers/archey/config.json).

Closing here for the time being as a PR is on its way.

Bye, thanks :bow:

**Comment by HorlogeSkynet** [comment]
Finally released in [v4.9.0](https://github.com/HorlogeSkynet/archey4/releases/tag/v4.9.0).
