### ISSUE TITLE
[FEATURE] Publish to Mac Homebrew

### ISSUE THREAD

**Issue by mdubinko** [HorlogeSkynet/archey4#96]
Make this project available on Mac Homebrew, ideally in the default tap.

I have not published anything on homebrew before, but as I understand it, there are multiple steps to it.

1. Create a new (or pick an existing) release to publish
2. Create a new repo called homebrew-archey4 (or some other name?)
3. Create the right Ruby formula there and commit
4. To get it on the default tap, create a pull request against the homebrew project

In the end, Mac install instructions should be simply

    brew install archey4

In case you are thinking of a different project name, before publishing would be the time to do it. :)
I'm partial to the name 'archier' but have no skin in the game.

**Comment by HorlogeSkynet** [comment]
Hello again @mdubinko.

Neither do I, and as I don't have access to a proper Homebrew macOS setup I guess I _shouldn't_ be the one proposing/maintaining this (actually, I wouldn't even pass their [PR template](https://github.com/Homebrew/homebrew-core/blob/master/.github/PULL_REQUEST_TEMPLATE.md)).

Would you be able to do it ?

I guess forking `Homebrew/homebrew-core` and create a `archey4.rb` formula would be sufficient before opening a PR.

Some pointers :

* [Official contributing guidelines](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md#to-add-a-new-formula-for-foo-version-234-from-url)
    * What about `brew create --python $URL` (from [here](https://docs.brew.sh/Formula-Cookbook#specifying-gems-python-modules-go-projects-etc-as-dependencies)) ?
* [Python for Formula Authors](https://docs.brew.sh/Python-for-Formula-Authors)
* [Jrnl](https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/jrnl.rb) example

I'd rather keep the same package/project name currently being used everywhere for consistency purposes.

Bye, thanks for your time :wave:

**Comment by HorlogeSkynet** [comment]
Hey back, I've finally taken the time to do it myself (with the help of [Homebrew on Linux](https://docs.brew.sh/Homebrew-on-Linux)).
See Homebrew/homebrew-core#74476.

Closing here.

**Comment by HorlogeSkynet** [comment]
Available ! <https://formulae.brew.sh/formula/archey4>
